### ISSUE TITLE
Something wrong

### ISSUE THREAD

**Issue by Balla2** [Lukeos11/MC-Server-Status-Bot#1]
Hello. Trying to get your bot up and running for my minecraft server. I'm recieving this error when launchet it.

Microsoft Windows [Version 10.0.17763.2237]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\bots\Minecraft>node index.js
C:\bots\Minecraft\node_modules\discord.js\src\rest\APIRequest.js:33
    agent ??= new https.Agent({ ...this.client.options.http.agent, keepAlive: true });
          ^^^

SyntaxError: Unexpected token '??='
[90m    at wrapSafe (internal/modules/cjs/loader.js:1001:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1049:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:950:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:12)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:93:18)[39m
    at Object.<anonymous> (C:\bots\Minecraft\node_modules\[4mdiscord.js[24m\src\rest\RESTManager.js:4:20)
[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)[39m

C:\bots\Minecraft>

Thank you.

**Comment by Lukeos11** [comment]
G'day

Can you please send me a screenshot of your console because of these � characters?
From looking at the error you have gotten, double-check that your token is correct and other information in the config and .env file is correct.

Sorry for the late response,
Luke.

**Comment by Karbon1** [comment]
Hey Lukeos11 how to update the placeholders it only shows {online}/{max} ill just edit the max but what about {online}

**Comment by Aflah2635** [comment]
server online placeholder like this With {online}/{max} then server is online help @Lukeos11

**Comment by Lukeos11** [comment]
@Karbon1 Please create another issue
